### ISSUE TITLE
As a prospective baseball team owner, I would like to be able to add my baseball team, and their corresponding stadium, to the program so that baseball tourists can visit my stadium too.

### ISSUE THREAD

**Issue by molinab297** [xavierliancw/Based-Itinerary#118]
Overview:
- The admin page has a button that says something like "add stadium"
- Clicking the button summons a dialog
- The dialog has empty fields to fill out, like team name, opening date, capacity, etc.
- The dialog has a cancel button and a save button
- After the dialog closes, the distance dialog opens automatically, and will not close until at least one connection is made to another stadium on the graph
- Requirement 2.7, 3.1, 3.2

Tasks:
- [x] Requires vector structure to hold stadium information
- [x] Create a class method to construct a new stadium object
- [x] Stadium name, team name, phone number, address, opening date, capacity, grass type, and stadium type should be parameters for that object construction
- [x] Make an error message if stadium name is left blank
- [x] Create a Qt Dialog class for adding a new stadium
- [x] Add in appropriate line edits
- [x] Make a save and cancel button
- [x] Create signal slot interface between the dialog and the prime window
- [x] Create a button on the admin page to open up the new dialog
- [x] Make an error message for any invalid characters in any field
- [x] Refresh the stadium list on the admin page if a new stadium is added to show that a new stadium exists
- [x] Make the distance dialog appear when saving the new stadium
- [x] The following checkbox must be done with a QMessageBox
- [x] Do not allow the distance dialog to be closed until at least one connection is made between the new stadium and an existing stadium

Definition of Done:
- [x] There is a button on the admin page
- [x] Clicking it pulls up a dialog that will add a new stadium
- [x] The dialog has fields for all of the stadium information laid out above
- [x] Error window pops up if invalid characters are type
- [x] Error window pops up if stadium name isn't specified
- [x] Error window pops up if stadium is not connected to the graph
- [x] Clicking save will add the stadium to the data structure
- [x] Clicking cancel will just close the dialog
- [x] If a new stadium is added, it appears everywhere it's supposed to in the program

**Comment by xavierliancw** [comment]
Lol, are you working on this?

**Comment by xavierliancw** [comment]
Lol, this replaces #16 since that was accidentally closed.

**Comment by xavierliancw** [comment]
Look at this commit:
https://github.com/xavierliancw/Based-Itinerary/commit/a2c4a5f52d748f430dffba238ac3f41f667725c7
