### ISSUE TITLE
As a baseball fan, I would like to be able to quickly identify which stadiums use grass surfaces so that I can add to my knowledge of baseball trivia.

### ISSUE THREAD

**Issue by xavierliancw** [xavierliancw/Based-Itinerary#5]
Overview:
- There is a checkbox that says something like "View Stadiums with Grass Surfaces Only"
- Clicking this checkbox applies a filter to the stadium listing such that only stadiums with grass surfaces are displayed
- Unchecking the checkbox will remove the filter
- Requirement 1.6, 3.1

Tasks:
- Requires a stadium listing on the home screen
- [ ] Create a grass filter checkbox on the home screen
- [ ] Create a function to filter out stadiums that do not use a grass surface
- [ ] Connect the checkbox to the grass filter function via signal/slot

Defintion of Done:
- [ ] There is a stadium listing on the home screen
- [ ] There is a checkbox to apply a filter to the listing such that only stadiums that use a grass surface are displayed
- [ ] Unchecking the checkbox disables the grass filter

**Comment by xavierliancw** [comment]
Why did I find this in the backlog? Did you move it @armanJafa ?

**Comment by armanJafa** [comment]
I didn't touch it at least I don't think I did. I selected the story to work on and I made one commit to branch. It's not ready to be reviewed yet though. Not sure how it ended up in the backlog

**Comment by xavierliancw** [comment]
Lol
